/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Gesa Rizky Nugraha
 */
public class Frameberatlain extends javax.swing.JFrame {

    /**
     * Creates new form Framepanjang
     */
    public Frameberatlain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        input = new javax.swing.JTextField();
        cmb_menu = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        outons = new javax.swing.JTextField();
        outpon = new javax.swing.JTextField();
        outkg = new javax.swing.JTextField();
        outkwintal = new javax.swing.JTextField();
        outton = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("KALKULATOR KONVERSI SATUAN BERAT");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Ons, Pon, Kg, Kwintal dan Ton (Isikan satuan awal, pilih dari satuan)");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Satuan Awal");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Satuan Dari");

        cmb_menu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih:", "Ons", "Pon", "Kg", "Kwintal", "Ton" }));
        cmb_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_menuActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Kesatuan");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Ons");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Pon");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Kilogram");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Kwintal");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Ton");

        outons.setEditable(false);

        outpon.setEditable(false);

        outkg.setEditable(false);

        outkwintal.setEditable(false);

        outton.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 14, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(input)
                                    .addComponent(cmb_menu, 0, 165, Short.MAX_VALUE)
                                    .addComponent(outons)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(outkg, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(outpon, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(outkwintal, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(outton, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmb_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(outons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(outpon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(outkg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(outkwintal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(outton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_menuActionPerformed
        // TODO add your handling code here:
        String teksinput = input.getText();
        double input = Double.parseDouble(teksinput); 
        if(cmb_menu.getSelectedIndex()==0)
        {
            outons.setText(null);
            outpon.setText(null);
            outkg.setText(null);
            outkwintal.setText(null);
            outton.setText(null);
        }
        if(cmb_menu.getSelectedIndex()==1)
        {
        double hasilinch = input * 1;
        String outputinch = String.valueOf(hasilinch);
        outons.setText(outputinch);
        double hasilkaki = input * 0.2;
        String outputkaki = String.valueOf(hasilkaki);
        outpon.setText(outputkaki);
        double hasilyard = input * 0.1;
        String outputyard = String.valueOf(hasilyard);
        outkg.setText(outputyard);
        double hasilmeter = input * 0.001;
        String outputmeter = String.valueOf(hasilmeter);
        outkwintal.setText(outputmeter);
        double hasilcenti = input * 0.0001;
        String outputcenti = String.valueOf(hasilcenti);
        outton.setText(outputcenti);
        }
        if(cmb_menu.getSelectedIndex()==2)
        {
        double hasilinch = input * 5;
        String outputinch = String.valueOf(hasilinch);
        outons.setText(outputinch);
        double hasilkaki = input * 1;
        String outputkaki = String.valueOf(hasilkaki);
        outpon.setText(outputkaki);
        double hasilyard = input * 0.5;
        String outputyard = String.valueOf(hasilyard);
        outkg.setText(outputyard);
        double hasilmeter = input * 0.005;
        String outputmeter = String.valueOf(hasilmeter);
        outkwintal.setText(outputmeter);
        double hasilcenti = input * 0.0005;
        String outputcenti = String.valueOf(hasilcenti);
        outton.setText(outputcenti);
        }
        if(cmb_menu.getSelectedIndex()==3)
        {
        double hasilinch = input * 10;
        String outputinch = String.valueOf(hasilinch);
        outons.setText(outputinch);
        double hasilkaki = input * 2;
        String outputkaki = String.valueOf(hasilkaki);
        outpon.setText(outputkaki);
        double hasilyard = input * 1;
        String outputyard = String.valueOf(hasilyard);
        outkg.setText(outputyard);
        double hasilmeter = input * 0.01;
        String outputmeter = String.valueOf(hasilmeter);
        outkwintal.setText(outputmeter);
        double hasilcenti = input * 0.001;
        String outputcenti = String.valueOf(hasilcenti);
        outton.setText(outputcenti);
        }
        if(cmb_menu.getSelectedIndex()==4)
        {
        double hasilinch = input * 1000;
        String outputinch = String.valueOf(hasilinch);
        outons.setText(outputinch);
        double hasilkaki = input * 200;
        String outputkaki = String.valueOf(hasilkaki);
        outpon.setText(outputkaki);
        double hasilyard = input * 100;
        String outputyard = String.valueOf(hasilyard);
        outkg.setText(outputyard);
        double hasilmeter = input * 1;
        String outputmeter = String.valueOf(hasilmeter);
        outkwintal.setText(outputmeter);
        double hasilcenti = input * 0.1;
        String outputcenti = String.valueOf(hasilcenti);
        outton.setText(outputcenti);
        }
        if(cmb_menu.getSelectedIndex()==5)
        {
        double hasilinch = input * 10000;
        String outputinch = String.valueOf(hasilinch);
        outons.setText(outputinch);
        double hasilkaki = input * 2000;
        String outputkaki = String.valueOf(hasilkaki);
        outpon.setText(outputkaki);
        double hasilyard = input * 1000;
        String outputyard = String.valueOf(hasilyard);
        outkg.setText(outputyard);
        double hasilmeter = input * 10;
        String outputmeter = String.valueOf(hasilmeter);
        outkwintal.setText(outputmeter);
        double hasilcenti = input * 1;
        String outputcenti = String.valueOf(hasilcenti);
        outton.setText(outputcenti);
        }
        
    }//GEN-LAST:event_cmb_menuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frameberatlain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frameberatlain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frameberatlain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frameberatlain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frameberatlain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmb_menu;
    private javax.swing.JTextField input;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField outkg;
    private javax.swing.JTextField outkwintal;
    private javax.swing.JTextField outons;
    private javax.swing.JTextField outpon;
    private javax.swing.JTextField outton;
    // End of variables declaration//GEN-END:variables
}
